name: Build
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
    workflow_dispatch:
jobs:
    build-and-deploy:
        runs-on: macos-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false
            - name: Install Deno 🦕
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - name: 'Build Executable'
              run: deno task build
            - name: Commit build artifacts ✅
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A && git commit -m "upd: add latest executables"
            - name: Push changes 🔼
              uses: ad-m/github-push-action@v0.6.0
              with:
                  repository: 'bridge-core/deno-dash-compiler'
                  branch: 'main'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
