name: Build
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
    workflow_dispatch:
jobs:
    build-and-deploy:
        runs-on: macos-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false
            - name: Install Deno 🦕
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - name: 'Build Executable'
              run: deno task build
            - name: Upload Executables
              uses: alexellis/upload-assets@0.3.0
              env:
                GITHUB_TOKEN: ${{ github.token }}
              with:
                asset_paths: '["./executables/*"]'
